name: testing
on: [push, pull_request]

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - env:
          TYPO3: "${{ matrix.typo3-version }}"
        name: "Install TYPO3 Core"
        run: |
          composer require --no-progress typo3/minimal:"$TYPO3"
          composer show
      - if: "matrix.composer-dependencies == 'lowest'"
        name: "Install lowest dependencies with composer"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies --prefer-lowest
          composer show
      - if: "matrix.composer-dependencies == 'highest'"
        name: "Install highest dependencies with composer"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies
          composer show
      - name: "Run unit tests"
        run: "composer ci:tests:unit"
    strategy:
      fail-fast: false
      matrix:
        composer-dependencies:
          - highest
          - lowest
        php-version:
          - 7.2
          - 7.3
          - 7.4
        typo3-version:
          - ^9.5
          - ^10.4


